// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaGnRwqFT52hfwvlrR5U7S3oAoijGccHc',
    appId: '1:934514708432:web:f9a043a17e8a805f37f3d5',
    messagingSenderId: '934514708432',
    projectId: 'perdidos-achados-da559',
    authDomain: 'perdidos-achados-da559.firebaseapp.com',
    storageBucket: 'perdidos-achados-da559.firebasestorage.app',
    measurementId: 'G-TMZ2N3G36Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzib5d8PLuejr4B11PC5_-2KOypSGJNPY',
    appId: '1:934514708432:android:dab4f31a41812f8437f3d5',
    messagingSenderId: '934514708432',
    projectId: 'perdidos-achados-da559',
    storageBucket: 'perdidos-achados-da559.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBrF-kYvlFcD7Qq0VmkWDlxno6oot7pw',
    appId: '1:934514708432:ios:edb18fb915b9d9c037f3d5',
    messagingSenderId: '934514708432',
    projectId: 'perdidos-achados-da559',
    storageBucket: 'perdidos-achados-da559.firebasestorage.app',
    iosBundleId: 'com.example.projetoProgMob',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATBrF-kYvlFcD7Qq0VmkWDlxno6oot7pw',
    appId: '1:934514708432:ios:edb18fb915b9d9c037f3d5',
    messagingSenderId: '934514708432',
    projectId: 'perdidos-achados-da559',
    storageBucket: 'perdidos-achados-da559.firebasestorage.app',
    iosBundleId: 'com.example.projetoProgMob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaGnRwqFT52hfwvlrR5U7S3oAoijGccHc',
    appId: '1:934514708432:web:1bf8f5fa4d4a527b37f3d5',
    messagingSenderId: '934514708432',
    projectId: 'perdidos-achados-da559',
    authDomain: 'perdidos-achados-da559.firebaseapp.com',
    storageBucket: 'perdidos-achados-da559.firebasestorage.app',
    measurementId: 'G-XBD2ZPTY3C',
  );
}
