// Uma lista de caminhos de imagens de exemplo pré-definidas.
// Estas imagens podem ser selecionadas pelos utilizadores como imagens de exemplo ao reportar um item,
// especialmente se não tiverem uma foto real do objeto perdido ou achado.
const List<String> assetImages = [
  'assets/mala.png',
  'assets/mala2.png',
  'assets/brincos.png',
  'assets/brincos2.png',
  'assets/carteira.png',
  'assets/carteira2.png',
  'assets/casaco.png',
  'assets/chave3.png',
  'assets/chaves1.png',
  'assets/chaves2.png',
  'assets/colar.png',
  'assets/colar2.png',
  'assets/colar3.png',
  'assets/colarsenhora.png',
  'assets/mochila.png',
  'assets/oculossol.png',
  'assets/passaport.png',
  'assets/pulseira.png',
  'assets/relogio.png',
  'assets/sporting.png',
  'assets/tablet.png',
  'assets/tele1.png',
  'assets/tele2.png',
  'assets/tele3.png',
];
